name: "Copilot Setup Steps"

# Allow testing of the setup steps from your repository's "Actions" tab.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      # Temporarily disable firewall to test if this resolves the issue
      COPILOT_AGENT_FIREWALL_ENABLED: false
      # If you want to re-enable firewall with allowlist, comment the line above and uncomment below:
      # COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: "storybook.js.org,*.storybook.js.org,cdn.jsdelivr.net,unpkg.com,fonts.googleapis.com,fonts.gstatic.com,raw.githubusercontent.com,github.com,api.github.com,npm.pkg.github.com,registry.npmjs.org,pkg-npm.npmjs.org"

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "vx.x.x"

      - name: Install Deno dependencies
        run: deno install
      - name: Install Playwright Browsers
        run: deno task install